### ISSUE TITLE
Removing files and folders in delta mode doesn't work

### ISSUE THREAD

**Issue by timocouckuyt** [milanmk/actions-file-deployer#3] opened 2021-11-25 08:06 UTC
Hey @milanmk,

Thanks for your work on this action! I needed to explore the possibility to deploy code over SSH so I stumbled upon this action, which works great, partly thanks to the delta/full sync switch, awesome! 

1 thing I noticed tho, is that when you create a testfolder with one testfile in it, that gets added perfectly fine, but if you remove the file from the testfolder and remove the folder too, in your repo, the removal of both file and folder doesn't work.

Could you check that, please?

Thanks a lot!

// T

**Comment by KingMike920** [comment] 2021-12-11 01:04
Hey @milanmk ,

thanks for your work on this action! I can confirm the issue of @timocouckuyt .
I have the same problem, too. @timocouckuyt  told that the problem is in delta-mode.
I just figured out that this problem exists in both modes - delta and full-mode.

Just follow the steps to reproduce of @timocouckuyt .

It would be great if you can fix this for us! You did such a great action on github :).
Many thanks for this!

**Comment by timocouckuyt** [comment] 2022-02-02 14:00
@milanmk Did you get the chance of looking into this issue?

**Comment by milanmk** [comment] 2022-02-02 16:50
I could reproduce this issue on my end. However, not sure what is causing it. Will post an update as soon as I find the fix for this issue.

**Comment by FranckSCTV** [comment] 2023-06-29 07:11
@ammar88 @milanmk 
Sorry for asking such a dumb question but is the following config syntax correct when using LFTP?
Doesn't seem to work so I'm obviously doing something wrong. (files aren't deleted on the server)

```
          sync: "full"
          ftp-mirror-options: "lftp --delete-first"
          debug: true
```

**Comment by milanmk** [comment] 2023-06-29 12:37
@FranckSCTV 
It should not contain the literal "lftp" command itself, just the option parameters.
```
ftp-mirror-options: "--delete-first"
```

**Comment by FranckSCTV** [comment] 2023-06-30 04:42
@milanmk 
Thank you! It actually worked that way. Really helped  A LOT.

**Closed** 2023-10-17 14:31 UTC
Labels: bug
